language: go

go:
  - 1.5
  - tip

env:
  - "PATH=/home/travis/gopath/bin:$PATH"
  matrix:
    - ES_VERSION=1.7.3

before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - if ! go get github.com/golang/tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi

before_script:
  # ElasticSearch Server
  - mkdir ${HOME}/elasticsearch
  - wget http://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-${ES_VERSION}.tar.gz
  - tar -xzf elasticsearch-${ES_VERSION}.tar.gz -C ${HOME}/elasticsearch
  - ${HOME}/elasticsearch/elasticsearch-${ES_VERSION}/bin/elasticsearch >& /dev/null &
  - sleep 15
  # Couchbase Server
  - sudo wget http://packages.couchbase.com/releases/3.0.3/couchbase-server-enterprise_3.0.3-debian7_amd64.deb
  - sudo dpkg -i couchbase-server-enterprise_3.0.3-debian7_amd64.deb
  - sudo service couchbase-server start
  # Setup Bucket for test
  # This is done explicitly in the tests now
  # Left here for refrence
  - sleep 15
  - /opt/couchbase/bin/couchbase-cli cluster-init -c 127.0.0.1:8091 --cluster-init-username=root --cluster-init-password=root123 --cluster-init-ramsize=1024
  - /opt/couchbase/bin/couchbase-cli bucket-create -c 127.0.0.1:8091 --bucket=test --bucket-password="" --bucket-type=couchbase --bucket-port=11211 --bucket-ramsize=124 --bucket-replica=0 -u root -p root123
  - sleep 20
  # Delete elastic search index
  - curl -XDELETE 'http://127.0.0.1:9200/testindex/'
  - sleep 10

script:
  - go test -v -covermode=count -coverprofile=coverage.out ./...
  - goveralls -coverprofile=coverage.out -service travis-ci -repotoken $COVERALLS_TOKEN

branches:
  only:
    - master
    - develop

email:
  - luigi@kreditech.com
  - tiago.amorim@kreditech.com
  - robert@kreditech.com
  - laura.hreniucu@kreditech.com